export enum ErrorCode {
  RequestValidationError = 'request_validation_error',
  UserAlreadyExist = 'user_already_exist',
  UserNotFound = 'user_not_found',
  UserHasNoPartner = 'user_has_no_partner',
  UserMaxLengthInvited = 'user_max_length_invited',
  MemberCreationError = 'member_creation_error',
  FeeCreationError = 'fee_creation_error',
  BadPaginationParameters = 'bad_pagination_parameters',
  BadFilterParameters = 'bad_filter_parameters',
  PasswordsNotMatch = 'passwords_not_match',
  AccessTokenNotValid = 'access_token_not_valid',
  AccessTokenExpired = 'access_token_expired',
  SetPasswordTokenIsNotValid = 'set_password_token_is_not_valid',
  SetPasswordTokenExpired = 'set_password_token_expired',
}
